version: "3.5"
services:
  tailscale:
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.84.2
    image: tailscale.dnp.dappnode.eth:0.1.0
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=
      - TS_ROUTES=172.33.0.0/16,10.20.0.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node
    volumes:
      - state:/var/lib/tailscale
    cap_add:
      - net_admin
      - sys_module
    devices:
      - /dev/net/tun:/dev/net/tun
volumes:
  state: null
