version: "3.5"
services:
  tailscale:
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.78
    image: tailscale.dnp.dappnode.eth:0.1.0
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=
      - ADVERTISE_ROUTES=172.33.0.0/16,10.20.0.0/24 # 172.33.0.0/16 is the current subnet in dappnode and 10.20.0.0/24 will be eventually used as the new subnet
      - EXTRA_OPTS=
    volumes:
      - state:/var/lib/tailscale
    cap_add:
      - net_admin
      - sys_module
    devices:
      - /dev/net/tun:/dev/net/tun
volumes:
  state:
